PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZONTA_OBJ_OC CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZONTA_OBJ_OC-ID .
    FIELD ZONTA_OBJ_OC-DOMAINV .
    FIELD ZONTA_OBJ_OC-BUSINESS_PROC .
    FIELD ZONTA_OBJ_OC-TYPE .
    FIELD ZONTA_OBJ_OC-DESCRIPTION .
    FIELD ZONTA_OBJ_OC-ERDAT .
    FIELD ZONTA_OBJ_OC-ERNAM .
    FIELD ZONTA_OBJ_OC-EVENTID .
    FIELD ZONTA_OBJ_OC-KSCHL .
    FIELD ZONTA_OBJ_OC-CDOBJECTCL .
    FIELD ZONTA_OBJ_OC-OBJTYPE .
    FIELD ZONTA_OBJ_OC-NO_REGISTROS .
    FIELD ZONTA_OBJ_OC-DATA .
    FIELD ZONTA_OBJ_OC-METADATA .
    FIELD ZONTA_OBJ_OC-TAG1 .
    FIELD ZONTA_OBJ_OC-TAG2 .
    FIELD ZONTA_OBJ_OC-TAG3 .
    FIELD ZONTA_OBJ_OC-TAG4 .
    FIELD ZONTA_OBJ_OC-TAG5 .
    FIELD ZONTA_OBJ_OC-LOG_TYPE .
    FIELD ZONTA_OBJ_OC-FILE_PATH .
    FIELD ZONTA_OBJ_OC-CLASS_NAME .
    FIELD ZONTA_OBJ_OC-UPDATED_ON .
    FIELD ZONTA_OBJ_OC-UPDATED_BY .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZONTA_OBJ_OC-ID .
    FIELD ZONTA_OBJ_OC-DOMAINV .
    FIELD ZONTA_OBJ_OC-BUSINESS_PROC .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
