PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZONTA_OC_VARIANT CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZONTA_OC_VARIANT-ID .
    FIELD ZONTA_OC_VARIANT-DOMAINV .
    FIELD ZONTA_OC_VARIANT-BUSINESS_PROC .
    FIELD ZONTA_OC_VARIANT-VARIANT .
    FIELD ZONTA_OC_VARIANT-TABNAME .
    FIELD ZONTA_OC_VARIANT-FIELDNAME .
    FIELD ZONTA_OC_VARIANT-VDESCRIPTION .
    FIELD ZONTA_OC_VARIANT-VARIANT_TYPE .
    FIELD ZONTA_OC_VARIANT-VTYPE .
    FIELD ZONTA_OC_VARIANT-SAPVAR .
    FIELD ZONTA_OC_VARIANT-DESCRIPTION .
    FIELD ZONTA_OC_VARIANT-SIGN .
    FIELD ZONTA_OC_VARIANT-OPTI .
    FIELD ZONTA_OC_VARIANT-VAL1 .
    FIELD ZONTA_OC_VARIANT-SIGN1 .
    FIELD ZONTA_OC_VARIANT-VAL2 .
    FIELD ZONTA_OC_VARIANT-SIGN2 .
    FIELD ZONTA_OC_VARIANT-CREATED_BY .
    FIELD ZONTA_OC_VARIANT-CREATED_ON .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZONTA_OC_VARIANT-ID .
    FIELD ZONTA_OC_VARIANT-DOMAINV .
    FIELD ZONTA_OC_VARIANT-BUSINESS_PROC .
    FIELD ZONTA_OC_VARIANT-VARIANT .
    FIELD ZONTA_OC_VARIANT-TABNAME .
    FIELD ZONTA_OC_VARIANT-FIELDNAME .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
