PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZONTA_RELATIONS CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZONTA_RELATIONS-ID .
    FIELD ZONTA_RELATIONS-DOMAINV .
    FIELD ZONTA_RELATIONS-BUSINESS_PROC .
    FIELD ZONTA_RELATIONS-TABNAME .
    FIELD ZONTA_RELATIONS-FIELD_MAIN .
    FIELD ZONTA_RELATIONS-FIELD_SEC .
    FIELD ZONTA_RELATIONS-PARENT_RELATION .
    FIELD ZONTA_RELATIONS-JOIN_TYPE .
    FIELD ZONTA_RELATIONS-SEQUENCE .
    FIELD ZONTA_RELATIONS-SUBSEQUENCE .
    FIELD ZONTA_RELATIONS-LEVELV .
    FIELD ZONTA_RELATIONS-ALIAS_TABNAME .
    FIELD ZONTA_RELATIONS-DESCRIPTION_TABLE .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZONTA_RELATIONS-ID .
    FIELD ZONTA_RELATIONS-DOMAINV .
    FIELD ZONTA_RELATIONS-BUSINESS_PROC .
    FIELD ZONTA_RELATIONS-TABNAME .
    FIELD ZONTA_RELATIONS-FIELD_MAIN .
    FIELD ZONTA_RELATIONS-FIELD_SEC .
    FIELD ZONTA_RELATIONS-PARENT_RELATION .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
