FUNCTION ZONFM_RS_DS_INT_SELDYN_2_EXPR.
*"--------------------------------------------------------------------
*"*"Local Interface:
*"  EXPORTING
*"     VALUE(P_TEXPR) TYPE  RSDS_TEXPR
*"  TABLES
*"      P_RSSELDYN STRUCTURE  RSSELDYN
*"      P_FIELDS STRUCTURE  RSDSFIELDS
*"--------------------------------------------------------------------

  DATA L_EXPR TYPE RSDS_EXPR.
  DATA L_RSDSEXPR LIKE RSDSEXPR.
  DATA L_TABANDINDEX LIKE SY-TABIX.
  DATA L_FIELDANDINDEX LIKE SY-TABIX.
  DATA L_I_OR_INDEX LIKE SY-TABIX.
  DATA L_E_OR_INDEX LIKE SY-TABIX.
  DATA L_FIELDNUM TYPE I.
  DATA L_I_NUM TYPE I.
  DATA L_E_NUM TYPE I.

  data:
    lt_rsseldyn TYPE STANDARD TABLE OF rsseldyn,
    ls_rsseldyn  TYPE rsseldyn.

  LT_RSSELDYN[] = P_RSSELDYN[].

  delete LT_RSSELDYN where sign  = space.

  SORT lt_RSSELDYN BY TABLENAME FIELDNAME SIGN DESCENDING.

  LOOP AT lt_RSSELDYN into P_RSSELDYN.

    AT NEW TABLENAME.
      MOVE P_RSSELDYN-TABLENAME TO:
                         L_EXPR-TABLENAME, P_FIELDS-TABLENAME.
      DESCRIBE TABLE L_EXPR-EXPR_TAB LINES SY-TFILL.
      L_TABANDINDEX = SY-TFILL + 1.
    ENDAT.
    AT NEW FIELDNAME.
      MOVE P_RSSELDYN-FIELDNAME TO P_FIELDS-FIELDNAME.
      APPEND P_FIELDS.
      DESCRIBE TABLE L_EXPR-EXPR_TAB LINES SY-TFILL.
      L_FIELDANDINDEX = SY-TFILL + 1.
      ADD 1 TO L_FIELDNUM.
    ENDAT.
    AT NEW SIGN.
      CASE P_RSSELDYN-SIGN.
        WHEN 'I'.
          DESCRIBE TABLE L_EXPR-EXPR_TAB LINES SY-TFILL.
          L_I_OR_INDEX = SY-TFILL + 1.
        WHEN 'E'.
          MOVE: 'NOT' TO L_RSDSEXPR-LOGOP,
                1     TO L_RSDSEXPR-ARITY.
          APPEND L_RSDSEXPR TO L_EXPR-EXPR_TAB.
          CLEAR L_RSDSEXPR.
          DESCRIBE TABLE L_EXPR-EXPR_TAB LINES SY-TFILL.
          L_E_OR_INDEX = SY-TFILL + 1.
*        WHEN space.
*          SUBTRACT 1 FROM L_FIELDNUM.
*          "CHECK 0 = 1.
      ENDCASE.
    ENDAT.

    CASE P_RSSELDYN-SIGN.
      WHEN 'I'.
        ADD 1 TO L_I_NUM.
      WHEN 'E'.
        ADD 1 TO L_E_NUM.
    ENDCASE.

    MOVE-CORRESPONDING P_RSSELDYN TO L_RSDSEXPR.
    APPEND L_RSDSEXPR TO L_EXPR-EXPR_TAB.
    CLEAR L_RSDSEXPR.

    AT END OF FIELDNAME.
      IF L_E_NUM > 1.
        MOVE: 'OR'    TO L_RSDSEXPR-LOGOP,
              L_E_NUM TO L_RSDSEXPR-ARITY.
        INSERT L_RSDSEXPR INTO L_EXPR-EXPR_TAB INDEX L_E_OR_INDEX.
        CLEAR L_RSDSEXPR.
      ENDIF.
      IF L_I_NUM > 1.
        MOVE: 'OR'    TO L_RSDSEXPR-LOGOP,
              L_I_NUM TO L_RSDSEXPR-ARITY.
        INSERT L_RSDSEXPR INTO L_EXPR-EXPR_TAB INDEX L_I_OR_INDEX.
        CLEAR L_RSDSEXPR.
      ENDIF.
      IF L_I_NUM > 0 AND L_E_NUM > 0.
        MOVE: 'AND'   TO L_RSDSEXPR-LOGOP,
              2       TO L_RSDSEXPR-ARITY.
        INSERT L_RSDSEXPR INTO L_EXPR-EXPR_TAB INDEX L_FIELDANDINDEX.
        CLEAR L_RSDSEXPR.
      ENDIF.
      CLEAR: L_I_NUM, L_E_NUM.
    ENDAT.

    AT END OF TABLENAME.
      CHECK L_FIELDNUM > 0.
      IF L_FIELDNUM > 1.
        MOVE: 'AND'       TO L_RSDSEXPR-LOGOP,
              L_FIELDNUM TO L_RSDSEXPR-ARITY.
        INSERT L_RSDSEXPR INTO L_EXPR-EXPR_TAB INDEX L_TABANDINDEX.
        CLEAR L_RSDSEXPR.
      ENDIF.
      APPEND L_EXPR TO P_TEXPR.
      CLEAR: L_FIELDNUM, L_EXPR.
    ENDAT.

  ENDLOOP.

  p_RSSELDYN[] = lt_RSSELDYN[].

ENDFUNCTION.
