PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZONTA_OC_CONV CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZONTA_OC_CONV-ID_COLUMN .
    FIELD ZONTA_OC_CONV-TABNAME .
    FIELD ZONTA_OC_CONV-ALIAS_TABNAME .
    FIELD ZONTA_OC_CONV-FLDNAME .
    FIELD ZONTA_OC_CONV-FLDNAME1 .
    FIELD ZONTA_OC_CONV-FLDNAME2 .
    FIELD ZONTA_OC_CONV-ALIAS_FLDNAME .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZONTA_OC_CONV-ID_COLUMN .
    FIELD ZONTA_OC_CONV-TABNAME .
    FIELD ZONTA_OC_CONV-ALIAS_TABNAME .
    FIELD ZONTA_OC_CONV-FLDNAME .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
