PROCESS BEFORE OUTPUT.
 MODULE STATUS_0281.
 module alv4_display.

PROCESS AFTER INPUT.
 MODULE USER_COMMAND_0281.
 MODULE USER_COMMAND_0281 at EXIT-COMMAND.
PROCESS ON VALUE-REQUEST.
  FIELD RSVAR-VARIANT module VARINAME_HELP.
