FUNCTION ZONFM_RS_DS_INT_ADJUST_SELID.
*"--------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(P_SELID) LIKE  RSDYNSEL-SELID
*"     VALUE(P_TEXPR) TYPE  RSDS_TEXPR
*"  EXPORTING
*"     VALUE(P_TWHERE) TYPE  RSDS_TWHERE
*"     VALUE(P_TRANGE) TYPE  RSDS_TRANGE
*"     VALUE(P_ACTNUM) LIKE  SY-TFILL
*"  TABLES
*"      P_VARIDYN STRUCTURE  RSVARIDYN
*"      P_VDATDYN STRUCTURE  RSVDATDYN OPTIONAL
*"  EXCEPTIONS
*"      SELID_NOT_FOUND
*"      EXPRESSION_NOT_SUPPORTED
*"      INCORRECT_EXPRESSION
*"--------------------------------------------------------------------

  DATA L_SUBRC LIKE SY-SUBRC.
  DATA L_TABIX LIKE SY-TABIX.
  DATA L_SELID_TABIX LIKE SY-TABIX.
  DATA L_FIELD_SEL TYPE FIELD_SEL_TYPE.
  DATA L_FIELD_SEL_T LIKE CURRENT_INFO-FIELD_SEL.

  DATA L_EXPR_FI_INDICES LIKE EXPR_FI_INDICES OCCURS 10
                   WITH HEADER LINE.
  DATA L_FIELDS LIKE RSDSFIELDS OCCURS 10 WITH HEADER LINE.

  READ TABLE SELID_INFO WITH KEY selid = P_SELID BINARY SEARCH
                        INTO CURRENT_INFO.
  L_SELID_TABIX = SY-TABIX.
  IF SY-SUBRC NE 0.
    RAISE SELID_NOT_FOUND.
  ENDIF.

  PERFORM FILL_P_FIELDS TABLES L_FIELDS.

  PERFORM BUILD_FIELD_SEL TABLES L_EXPR_FI_INDICES
                          USING    P_TEXPR
                          CHANGING L_FIELD_SEL_T
                                   L_SUBRC.
  CASE L_SUBRC.
    WHEN 0.
    WHEN 4.               " Nicht unterstützter Ausdruck
      RAISE EXPRESSION_NOT_SUPPORTED.
    WHEN 8.               " Inkorrekter Ausdruck
      RAISE INCORRECT_EXPRESSION.
  ENDCASE.

  DESCRIBE TABLE L_FIELD_SEL_T LINES P_ACTNUM.
  MOVE P_ACTNUM TO CURRENT_INFO-ACTNUM.

  PERFORM SORT_AND_FILL_FIELD_SEL TABLES   L_FIELDS
                                  USING    CURRENT_INFO-KIND
                                           L_FIELD_SEL_T
                                  CHANGING CURRENT_INFO-FIELD_SEL.

  LOOP AT P_VARIDYN.
    READ TABLE CURRENT_INFO-FIELD_SEL WITH KEY
               TABLENAME = P_VARIDYN-TABLENAME
               FIELDNAME = P_VARIDYN-FIELDNAME
               INTO L_FIELD_SEL.
    CHECK SY-SUBRC = 0.
    L_TABIX = SY-TABIX.
    MOVE: P_VARIDYN-PROTECTED TO L_FIELD_SEL-PROTECTED,
          P_VARIDYN-VTYPE     TO L_FIELD_SEL-VTYPE.
    MODIFY CURRENT_INFO-FIELD_SEL FROM L_FIELD_SEL INDEX L_TABIX.
  ENDLOOP.

  perFORM FILL_SELOPTS_FROM_FIELD_SEL
                   USING CURRENT_INFO-FIELD_SEL.

  PERFORM GEN_WHERE_CLAUSES USING    CURRENT_INFO
                   CHANGING P_TWHERE
                            L_SUBRC.

  PERFORM BUILD_TRANGE USING    CURRENT_INFO-FIELD_SEL
                                CURRENT_INFO-ANY_JOINS
                       CHANGING P_TRANGE.

  MODIFY SELID_INFO INDEX L_SELID_TABIX FROM CURRENT_INFO.

ENDFUNCTION.
