PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZONTA_OC_COLUMNS CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZONTA_OC_COLUMNS-DOMAINV .
    FIELD ZONTA_OC_COLUMNS-BUSINESS_PROC .
    FIELD ZONTA_OC_COLUMNS-TABNAME .
    FIELD ZONTA_OC_COLUMNS-FLDNAME .
    FIELD ZONTA_OC_COLUMNS-ALIAS_FLDNAME .
    FIELD ZONTA_OC_COLUMNS-KEY_FIELD .
    FIELD ZONTA_OC_COLUMNS-SELECTION_FIELD .
    FIELD ZONTA_OC_COLUMNS-DESCRIPTION_FIELD .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZONTA_OC_COLUMNS-DOMAINV .
    FIELD ZONTA_OC_COLUMNS-BUSINESS_PROC .
    FIELD ZONTA_OC_COLUMNS-TABNAME .
    FIELD ZONTA_OC_COLUMNS-FLDNAME .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
