PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZONTA_OC_AUTH CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZONTA_OC_AUTH-ID .
    FIELD ZONTA_OC_AUTH-OBJCT .
    FIELD ZONTA_OC_AUTH-FIEL1 .
    FIELD ZONTA_OC_AUTH-FIEL2 .
    FIELD ZONTA_OC_AUTH-FIEL3 .
    FIELD ZONTA_OC_AUTH-FIEL4 .
    FIELD ZONTA_OC_AUTH-FIEL5 .
    FIELD ZONTA_OC_AUTH-FIEL6 .
    FIELD ZONTA_OC_AUTH-FIEL7 .
    FIELD ZONTA_OC_AUTH-FIEL8 .
    FIELD ZONTA_OC_AUTH-FIEL9 .
    FIELD ZONTA_OC_AUTH-FIEL0 .
    FIELD ZONTA_OC_AUTH-VAL1 .
    FIELD ZONTA_OC_AUTH-VAL2 .
    FIELD ZONTA_OC_AUTH-VAL3 .
    FIELD ZONTA_OC_AUTH-VAL4 .
    FIELD ZONTA_OC_AUTH-VAL5 .
    FIELD ZONTA_OC_AUTH-VAL6 .
    FIELD ZONTA_OC_AUTH-VAL7 .
    FIELD ZONTA_OC_AUTH-VAL8 .
    FIELD ZONTA_OC_AUTH-VAL9 .
    FIELD ZONTA_OC_AUTH-VAL10 .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZONTA_OC_AUTH-ID .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
