PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZONTA_DATAPRODC CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZONTA_DATAPRODC-PROCESS_PREFIX .
    FIELD ZONTA_DATAPRODC-SPRAS .
    FIELD ZONTA_DATAPRODC-MMODULE .
    FIELD ZONTA_DATAPRODC-SMODULE .
    FIELD ZONTA_DATAPRODC-E2E .
    FIELD ZONTA_DATAPRODC-LOB .
    FIELD ZONTA_DATAPRODC-SOLUTION_PG .
    FIELD ZONTA_DATAPRODC-SUBMODULE_NAME .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZONTA_DATAPRODC-PROCESS_PREFIX .
    FIELD ZONTA_DATAPRODC-SPRAS .
    FIELD ZONTA_DATAPRODC-MMODULE .
    FIELD ZONTA_DATAPRODC-SMODULE .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
