FUNCTION ZONFM_RS_DS_INT_BREPI.
*"--------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(P_TEXPR) TYPE  RSDS_TEXPR
*"     VALUE(P_EDIT) DEFAULT SPACE
*"  TABLES
*"      P_FIELDS STRUCTURE  RSDSFIELDS
*"      P_VALUES STRUCTURE  RSSELDYN
*"      P_DESC STRUCTURE  RSDYNBREPI
*"      P_NODES_TO_STRUCT STRUCTURE  NODE2STRUC OPTIONAL
*"  EXCEPTIONS
*"      EXP_FIELD_NOT_IN_FIELD_TAB
*"      EXPRESSION_NOT_SUPPORTED
*"      INCORRECT_EXPRESSION
*"      EXP_FIELD_NOT_IN_TABLE
*"--------------------------------------------------------------------

  DATA: BEGIN OF L_TABS OCCURS 5,
          TABLENAME LIKE RSDSTABS-PRIM_TAB,
        END   OF L_TABS.

  DATA: BEGIN OF L_EXPR_FI_INDICES OCCURS 10.
          INCLUDE STRUCTURE EXPR_FI_INDICES.
  DATA: END   OF L_EXPR_FI_INDICES.

  DATA L_SUBRC LIKE SY-SUBRC.
  DATA L_TABIX LIKE SY-TABIX VALUE 1.
  DATA L_FIELD_SEL TYPE FIELD_SEL_TYPE.
  DATA L_FIELD_SEL_T LIKE CURRENT_INFO-FIELD_SEL.
  DATA L_RSDSSELOPT LIKE RSDSSELOPT.
  DATA L_INITIAL_LOW.
  DATA L_INITIAL_HIGH.
  DATA L_FLAG_NODES.

  DATA: BEGIN OF L_SELNAME,
          PREFIX(5) VALUE '%_DSS',
          SUFFIX(3) TYPE N,
        END   OF L_SELNAME.

  DATA L_CTX_DD TYPE CONTEXT_FREE_SEL_DD_INFO.
  DATA L_MSG    LIKE SYMSG OCCURS 0.
  DATA L_MAX_LENG TYPE I.

  IF NOT P_NODES_TO_STRUCT[] IS INITIAL.
     L_FLAG_NODES = 'X'.
  ENDIF.
  data l_info like current_info.
  l_info = current_info.
  clear current_info.

  PERFORM BUILD_FIELD_SEL TABLES L_EXPR_FI_INDICES
                          USING    P_TEXPR
                          CHANGING L_FIELD_SEL_T L_SUBRC.
  current_info = l_info.

  CASE L_SUBRC.
    WHEN 0.
    WHEN 4.               " Nicht unterstützter Ausdruck
      RAISE EXPRESSION_NOT_SUPPORTED.
    WHEN 8.               " Inkorrekter Ausdruck
      RAISE INCORRECT_EXPRESSION.
  ENDCASE.

  LOOP AT L_FIELD_SEL_T INTO L_FIELD_SEL.
    READ TABLE P_FIELDS WITH KEY tablename = L_FIELD_SEL-TABLENAME
                                 fieldname = L_FIELD_SEL-FIELDNAME.
    IF SY-SUBRC NE 0.
      DELETE L_FIELD_SEL_T.
    ENDIF.
  ENDLOOP.

  LOOP AT L_FIELD_SEL_T INTO L_FIELD_SEL.
    READ TABLE P_FIELDS WITH KEY tablename = L_FIELD_SEL-TABLENAME
                                 fieldname = L_FIELD_SEL-FIELDNAME.
    IF SY-SUBRC NE 0.
      RAISE EXP_FIELD_NOT_IN_FIELD_TAB.
    ENDIF.
    MOVE SY-TABIX TO L_SELNAME-SUFFIX.
    MOVE L_FIELD_SEL-TABLENAME TO: P_VALUES-TABLENAME,
                                   P_DESC-TABLENAME.
    MOVE L_FIELD_SEL-FIELDNAME TO: P_VALUES-FIELDNAME,
                                   P_DESC-FIELDNAME.
    IF NOT L_FLAG_NODES IS INITIAL.
      READ TABLE P_NODES_TO_STRUCT WITH KEY               "#EC *
                       LDBNODE = L_FIELD_SEL-TABLENAME.
      IF SY-SUBRC = 0 AND NOT P_NODES_TO_STRUCT-STRUCTURE IS INITIAL.
        L_FIELD_SEL-TABLENAME = P_NODES_TO_STRUCT-STRUCTURE.
      ENDIF.
    ENDIF.
    SUPPLY TABLENAME = L_FIELD_SEL-TABLENAME
           FIELDNAME = L_FIELD_SEL-FIELDNAME
           TO CONTEXT L_CTX_DD.
    DEMAND SELTEXT     = L_FIELD_SEL-TEXT
           CONVERT     = L_FIELD_SEL-CONVERT
           FROM CONTEXT L_CTX_DD
           MESSAGES INTO L_MSG.
    IF SY-SUBRC NE 0.
      RAISE EXP_FIELD_NOT_IN_TABLE.
    ENDIF.
    DESCRIBE FIELD RSDSINTERN-SELOPT LENGTH L_MAX_LENG in character
      mode.
    IF L_FIELD_SEL-CONVERT-OLENGTH > L_MAX_LENG.
      L_FIELD_SEL-CONVERT-OLENGTH = L_MAX_LENG.
    ENDIF.
    P_DESC-SEL_TEXT = L_FIELD_SEL-TEXT.
    P_DESC-OLEN = L_FIELD_SEL-CONVERT-OLENGTH.
    APPEND P_DESC.
    LOOP AT L_FIELD_SEL-FIELDSEL INTO L_RSDSSELOPT.
      ADD 1 TO L_TABIX.
      IF P_EDIT NE SPACE.
        PERFORM CONVERT_WH_2_EX(RSDYNSS0) USING   L_FIELD_SEL-CONVERT
                                                  L_RSDSSELOPT-LOW
                                         CHANGING P_VALUES-LOW
                                                  L_INITIAL_LOW.
        PERFORM CONVERT_WH_2_EX(RSDYNSS0) USING   L_FIELD_SEL-CONVERT
                                                  L_RSDSSELOPT-HIGH
                                         CHANGING P_VALUES-HIGH
                                                  L_INITIAL_HIGH.
        MOVE: L_RSDSSELOPT-SIGN   TO P_VALUES-SIGN,
              L_RSDSSELOPT-OPTION TO P_VALUES-OPTION.
      ELSE.
        MOVE-CORRESPONDING L_RSDSSELOPT TO P_VALUES.
      ENDIF.
      APPEND P_VALUES.
    ENDLOOP.
  ENDLOOP.
ENDFUNCTION.
