PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZONTA_OC_COL_ALL CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZONTA_OC_COL_ALL-ID_COLUMN .
    FIELD ZONTA_OC_COL_ALL-TABNAME .
    FIELD ZONTA_OC_COL_ALL-ALIAS_TABNAME .
    FIELD ZONTA_OC_COL_ALL-FLDNAME .
    FIELD ZONTA_OC_COL_ALL-ALIAS_FLDNAME .
    FIELD ZONTA_OC_COL_ALL-KEY_FIELD .
    FIELD ZONTA_OC_COL_ALL-SELECTION_FIELD .
    FIELD ZONTA_OC_COL_ALL-DESCRIPTION_FIELD .
    FIELD ZONTA_OC_COL_ALL-SECKEY_FIELD .
    FIELD ZONTA_OC_COL_ALL-POSITIONF .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZONTA_OC_COL_ALL-ID_COLUMN .
    FIELD ZONTA_OC_COL_ALL-TABNAME .
    FIELD ZONTA_OC_COL_ALL-ALIAS_TABNAME .
    FIELD ZONTA_OC_COL_ALL-FLDNAME .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
