FUNCTION ZONFM_FREE_SELECTIONS_LDB_FIE.
*"--------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(P_QU_KEY) TYPE  RSDSQCAT
*"  TABLES
*"      FIELD_NAMES STRUCTURE  RSDSQFN
*"      FUNCTION_ID STRUCTURE  RSDSQGN OPTIONAL
*"  EXCEPTIONS
*"      NO_VIEW
*"--------------------------------------------------------------------
*
* This FM can be used in FORM PBO in a LDB.
*
  DATA: L_QU_GROUP_FI TYPE QU_GROUP_FI_TYPE,
       L_TABIX TYPE SY-TABIX,
       L_LINES TYPE SY-TABIX.
  DATA: L_RSDSQCAT TYPE RSDSQCAT.

  FIELD-SYMBOLS: <L_GENERIC_FIELD> LIKE GENERIC_EXTENDED_FIELD,
                 <L_QU_GROUP_FI> TYPE QU_GROUP_FI_TYPE,
                 <L_QU_SEL>      TYPE FIELD_SEL_TYPE.
  FIELD-SYMBOLS: <W_SELID> TYPE SELID_INFO_LINE_TYPE.

  SELECT SINGLE * FROM RSDSQCAT INTO L_RSDSQCAT
                                WHERE ORIGIN = P_QU_KEY-ORIGIN AND
                                      DBNA   = P_QU_KEY-DBNA   AND
                                      NAME   = P_QU_KEY-NAME.
  IF SY-SUBRC <> 0.
    RAISE NO_VIEW.
  ENDIF.

  READ TABLE LDB WITH KEY LDBNAME = P_QU_KEY-DBNA.
  IF SY-SUBRC = 0.
    READ TABLE SELID_INFO WITH KEY SELID = LDB-SELID ASSIGNING <W_SELID>.
    DESCRIBE TABLE <W_SELID>-GROUPS LINES L_LINES.
    IF L_LINES > 0.
      LOOP AT <W_SELID>-GROUPS ASSIGNING <L_QU_GROUP_FI>.
        READ TABLE FUNCTION_ID WITH KEY NUMB = <L_QU_GROUP_FI>-NUMB.
        IF SY-SUBRC = 0.
          DELETE TABLE <W_SELID>-GROUPS FROM <L_QU_GROUP_FI>.
          CONTINUE.
        ENDIF.
        LOOP AT <L_QU_GROUP_FI>-FIELDS ASSIGNING <L_GENERIC_FIELD>.
          L_TABIX = SY-TABIX.
          READ TABLE FIELD_NAMES WITH KEY TAB = <L_GENERIC_FIELD>-TABLENAME
                                     FNAME = <L_GENERIC_FIELD>-FIELDNAME.
          IF SY-SUBRC = 0.
            DELETE <L_QU_GROUP_FI>-FIELDS INDEX L_TABIX.
          ENDIF.

        ENDLOOP.
      ENDLOOP.

      DATA: L_FIELD_SEL   TYPE FIELD_SEL_TYPE OCCURS 5.

      LOOP AT <W_SELID>-FIELD_SEL ASSIGNING <L_QU_SEL>.
        L_TABIX = SY-TABIX.
        READ TABLE FUNCTION_ID WITH KEY NUMB = <L_QU_SEL>-QU_NUM.
        IF SY-SUBRC = 0.
          DELETE TABLE <W_SELID>-FIELD_SEL FROM <L_QU_SEL>.
          CONTINUE.
        ENDIF.
        READ TABLE FIELD_NAMES WITH KEY TAB = <L_QU_SEL>-TABLENAME
                                   FNAME = <L_QU_SEL>-FIELDNAME.
        IF SY-SUBRC = 0.
          DELETE <W_SELID>-FIELD_SEL INDEX L_TABIX.
        ENDIF.
      ENDLOOP.
    ENDIF.

  ENDIF.

ENDFUNCTION.
