FUNCTION ZONFM_FREE_SELECTIONS_LDBJOINS.
*"--------------------------------------------------------------------
*"*"Local Interface:
*"  TABLES
*"      TABLES_TAB STRUCTURE  RSDSTABS OPTIONAL
*"      FIELD_TEXTS STRUCTURE  RSDSTEXTS OPTIONAL
*"  EXCEPTIONS
*"      FIELDS_INCOMPLETE
*"      FIELD_NOT_FOUND
*"      LDB_INIT_REPEAT
*"      LDB_INIT_TOO_LATE
*"      TABLE_NOT_FOUND
*"      TABLE_NO_JOIN
*"      LDB_NO_NODES
*"      ILLEGAL_LDB
*"      NODE_NOT_IN_LDB
*"--------------------------------------------------------------------

  DATA L_INT TYPE I.
  DATA L_SUBRC LIKE SY-SUBRC.
  DATA L_TABIX  LIKE SY-TABIX.
  DATA L_NODES TYPE NODE_T_TYPE.
  DATA L_N_T_T TYPE N_2_T_TYPE.
  DATA L_N_T   TYPE N_2_T_LINE_TYPE.
  DATA L_LDBNAME LIKE LDBD-LDBNAME.
  DATA L_LDB_EX.
  DATA L_CLIENT_POS LIKE SY-TABIX.
  DATA L_LDB_TABIX LIKE SY-TABIX.
  DATA L_LDB_SUBRC LIKE SY-SUBRC.
  DATA L_LDB_TFILL LIKE SY-TFILL.

  DATA: BEGIN OF L_TABS OCCURS 10,
          TABLENAME LIKE RSDSTABS-PRIM_TAB,
        END   OF L_TABS.

  DATA: BEGIN OF L_JOINS OCCURS 10,
          TABLENAME LIKE RSDSTABS-PRIM_TAB,
        END   OF L_JOINS.

  IF G_LDBNAME IS INITIAL.
    CALL FUNCTION 'LDB_CONVERT_DBPROG_2_LDBNAME'
         EXPORTING
              DBPROG                    = SY-LDBPG
              FLAG_EXISTENCE_CHECK      = 'X'
         IMPORTING
              LDBNAME                   = L_LDBNAME
              FLAG_DBPROG_EXISTENT      = L_LDB_EX
         EXCEPTIONS
              OTHERS                    = 1.
    IF SY-SUBRC NE 0 OR L_LDB_EX = SPACE.
      RAISE ILLEGAL_LDB.
    ENDIF.
  ELSE.
    L_LDBNAME = G_LDBNAME.
  ENDIF.

  READ TABLE LDB WITH KEY ldbname = l_LDBNAME BINARY SEARCH.
  L_LDB_TABIX = SY-TABIX.
  L_LDB_SUBRC = SY-SUBRC.
  L_LDB_TFILL = SY-TFILL.
  IF L_LDB_SUBRC NE 0.
    CLEAR LDB.
    MOVE: L_LDBNAME TO LDB-LDBNAME,
          'LD' TO LDB-SELID(2).
    UNPACK L_LDB_TFILL TO LDB-SELID+2(6).
  ENDIF.
  IF LDB-INIT_JOINS NE SPACE.
    RAISE LDB_INIT_REPEAT.
  ENDIF.
  IF LDB-INIT NE SPACE.
    RAISE LDB_INIT_TOO_LATE.
  ENDIF.
  MOVE 'X' TO LDB-INIT_JOINS.

  PERFORM FILL_NOTA USING    L_LDBNAME
                    CHANGING L_NODES
                             L_N_T_T.
  IF L_N_T_T IS INITIAL.
    RAISE LDB_NO_NODES.
  ENDIF.

  LOOP AT TABLES_TAB.
    CLEAR L_TABS.
    IF TABLES_TAB-SEC_TAB = SPACE.
      RAISE TABLE_NO_JOIN.
    ENDIF.
    READ TABLE L_N_T_T INTO L_N_T                          "#EC *
             WITH KEY LDBNODE = TABLES_TAB-SEC_TAB
             BINARY SEARCH
             TRANSPORTING STRUCTURE.
    IF SY-SUBRC NE 0.
      RAISE NODE_NOT_IN_LDB.
    ENDIF.
    READ TABLE L_JOINS WITH KEY
           tablename = TABLES_TAB-PRIM_TAB BINARY SEARCH.
    IF SY-SUBRC NE 0.
      L_TABIX = SY-TABIX.
      MOVE: L_TABS-TABLENAME TO L_JOINS-TABLENAME.
      INSERT L_JOINS INDEX L_TABIX.
    ENDIF.

    CLEAR L_INT.
    IF TABLES_TAB-PRIM_FNAME NE SPACE.
      ADD 1 TO L_INT.
    ENDIF.
    IF TABLES_TAB-SEC_FNAME NE SPACE.
      ADD 2 TO L_INT.
    ENDIF.

    CASE L_INT.
      WHEN 1.                  " nur PRIM_FNAME ungleich SPACE
        RAISE FIELDS_INCOMPLETE.
      WHEN 2.                  " nur SEC_FNAME ungleich SPACE
        PERFORM CHECK_FIELD_IN_DDIC USING
                   L_N_T-STRUCTURE    TABLES_TAB-SEC_FNAME L_SUBRC.
        IF L_SUBRC NE 0.
          RAISE FIELD_NOT_FOUND.
        ENDIF.
      WHEN 3.                  " zwei Feldnamen angegeben.
        PERFORM CHECK_FIELD_IN_DDIC USING
                   L_N_T-STRUCTURE    TABLES_TAB-SEC_FNAME L_SUBRC.
        IF L_SUBRC NE 0.
          RAISE FIELD_NOT_FOUND.
        ENDIF.
    ENDCASE.
    MOVE L_N_T-STRUCTURE    TO L_TABS-TABLENAME.
    PERFORM CHECK_TAB_IN_DDIC USING L_TABS-TABLENAME
                          CHANGING L_CLIENT_POS L_SUBRC.
    IF L_SUBRC NE 0.
      RAISE TABLE_NOT_FOUND.
    ENDIF.
    COLLECT L_TABS.
  ENDLOOP.

  LDB-TABS_AND_JOINS = TABLES_TAB[].
  LDB-TEXTS          = FIELD_TEXTS[].
  SORT LDB-TEXTS BY TABLENAME FIELDNAME.

  IF L_LDB_SUBRC = 0.
    MODIFY LDB INDEX L_LDB_TABIX.
  ELSE.
    INSERT LDB INDEX L_LDB_TABIX.
  ENDIF.

ENDFUNCTION.
