PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZONTA_OC_PARAM CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZONTA_OC_PARAM-NAME .
    FIELD ZONTA_OC_PARAM-TYPE .
    FIELD ZONTA_OC_PARAM-NUMB .
    FIELD ZONTA_OC_PARAM-SIGN .
    FIELD ZONTA_OC_PARAM-OPTI .
    FIELD ZONTA_OC_PARAM-LOW .
    FIELD ZONTA_OC_PARAM-HIGH .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZONTA_OC_PARAM-NAME .
    FIELD ZONTA_OC_PARAM-TYPE .
    FIELD ZONTA_OC_PARAM-NUMB .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
