PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZONTA_OC_FETCH_R CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZONTA_OC_FETCH_R-UUID_REC .
    FIELD ZONTA_OC_FETCH_R-INSTID .
    FIELD ZONTA_OC_FETCH_R-TYPEID .
    FIELD ZONTA_OC_FETCH_R-CATID .
    FIELD ZONTA_OC_FETCH_R-EVENT .
    FIELD ZONTA_OC_FETCH_R-ZDATE .
    FIELD ZONTA_OC_FETCH_R-TIME .
    FIELD ZONTA_OC_FETCH_R-ERNAM .
    FIELD ZONTA_OC_FETCH_R-DESTINATION .
    FIELD ZONTA_OC_FETCH_R-STATUS_HEADER .
    FIELD ZONTA_OC_FETCH_R-LAST_CHANGE_DATETIME .
    FIELD ZONTA_OC_FETCH_R-CREATION_DATIME .
    FIELD ZONTA_OC_FETCH_R-CREATION_USER .
    FIELD ZONTA_OC_FETCH_R-LAST_CHANGE_USER .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZONTA_OC_FETCH_R-UUID_REC .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
