FUNCTION ZONFMFREE_SELECTIONS_RANGE2WH.
*"--------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(FIELD_RANGES) TYPE  RSDS_TRANGE
*"  EXPORTING
*"     VALUE(WHERE_CLAUSES) TYPE  RSDS_TWHERE
*"--------------------------------------------------------------------

  DATA L_RANGE TYPE RSDS_RANGE.
  DATA L_FRANGE TYPE RSDS_FRANGE.
  DATA L_RSDSSELOPT LIKE RSDSSELOPT.
  DATA L_FLENG TYPE I.
  DATA L_FIELD_SEL   TYPE FIELD_SEL_TYPE.
  DATA L_INFO LIKE CURRENT_INFO.
  DATA L_SUBRC LIKE SY-SUBRC.

  LOOP AT FIELD_RANGES INTO L_RANGE.
    DESCRIBE TABLE L_RANGE-FRANGE_T LINES SY-TFILL.
    CHECK SY-TFILL > 0.
    MOVE L_RANGE-TABLENAME TO L_FIELD_SEL-TABLENAME.
    LOOP AT L_RANGE-FRANGE_T INTO L_FRANGE.
      DESCRIBE TABLE L_FRANGE-SELOPT_T LINES SY-TFILL.
      CHECK SY-TFILL > 0.
      MOVE L_FRANGE-FIELDNAME TO L_FIELD_SEL-FIELDNAME.
      CLEAR L_FIELD_SEL-CONVERT.
      L_FIELD_SEL-CONVERT-TYPE = 'C'.
      LOOP AT L_FRANGE-SELOPT_T INTO L_RSDSSELOPT.
        L_FLENG = STRLEN( L_RSDSSELOPT-LOW ).
        IF L_FLENG = 0.
          L_FLENG = 1.
        ENDIF.
        IF L_FLENG > L_FIELD_SEL-CONVERT-cLENGTH.
          L_FIELD_SEL-CONVERT-cLENGTH = L_FLENG.
        ENDIF.
        L_FLENG = STRLEN( L_RSDSSELOPT-HIGH ).
        IF L_FLENG > L_FIELD_SEL-CONVERT-cLENGTH.
          L_FIELD_SEL-CONVERT-cLENGTH = L_FLENG.
        ENDIF.
        APPEND L_RSDSSELOPT TO L_FIELD_SEL-FIELDSEL.
      ENDLOOP.
      L_FIELD_SEL-CONVERT-OLENGTH = L_FIELD_SEL-CONVERT-WHERE_LENG =
                                    L_FIELD_SEL-CONVERT-cLENGTH.
      l_field_sel-convert-length =
        L_FIELD_SEL-CONVERT-cLENGTH * CL_ABAP_CHAR_UTILITIES=>charsize.
      APPEND L_FIELD_SEL TO L_INFO-FIELD_SEL.
      CLEAR L_FIELD_SEL-FIELDSEL.
    ENDLOOP.
  ENDLOOP.

  PERFORM GEN_WHERE_FROM_FIELDS_NEW USING    L_INFO
                            CHANGING WHERE_CLAUSES L_SUBRC.

ENDFUNCTION.
