***INCLUDE RSDBCOM3.
* Meldungsstruktur für Selektionsbildgenerierung
* RSSYSTDB / RSDBGENA ...
TYPES: BEGIN OF SCR_MESS_TYPE,
         CODE(5),
         DYNNR LIKE SY-DYNNR,
         MESSAGE(160),
         DYNPRO_WORD(30),
         DYNPRO_LINE TYPE I,
         DYNPRO_COLN TYPE I,
         DYNPRO_FRAME_END TYPE I,
         SSCR_TABIX LIKE SY-TABIX,
         SSCR LIKE RSSCR,
       END OF SCR_MESS_TYPE.
DATA: GEN_MESSAGE TYPE SCR_MESS_TYPE.
* Tabelle der Bilder
TYPES: SCR_MESS_T_TYPE TYPE SCR_MESS_TYPE OCCURS 5.
DATA: MESSTAB TYPE SCR_MESS_T_TYPE.
