***INCLUDE RSDYNSC2.

* ------- Unsichtbare SELECT-OPTIONS --------------------------------- *

* Integers
SELECTION-SCREEN BEGIN OF BLOCK INT.
SELECT-OPTIONS %%INT001 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT002 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT003 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT004 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT005 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT006 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT007 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT008 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT009 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT010 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT011 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT012 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT013 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT014 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT015 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT016 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT017 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT018 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT019 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT020 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT021 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT022 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT023 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT024 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT025 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT026 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT027 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT028 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT029 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT030 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT031 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT032 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT033 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT034 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT035 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT036 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT037 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT038 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT039 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT040 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT041 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT042 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT043 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT044 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT045 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT046 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT047 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT048 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT049 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT050 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT051 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT052 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT053 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT054 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT055 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT056 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT057 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT058 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT059 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT060 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT061 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT062 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT063 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT064 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT065 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT066 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT067 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT068 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT069 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT070 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT071 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT072 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT073 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT074 FOR GL-INTEGER NO-DISPLAY.
SELECT-OPTIONS %%INT075 FOR GL-INTEGER NO-DISPLAY.
SELECTION-SCREEN END   OF BLOCK INT.

* INT8
SELECT-OPTIONS %%IN8001 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8002 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8003 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8004 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8005 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8006 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8007 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8008 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8009 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8010 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8011 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8012 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8013 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8014 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8015 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8016 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8017 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8018 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8019 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8020 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8021 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8022 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8023 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8024 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8025 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8026 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8027 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8028 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8029 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8030 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8031 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8032 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8033 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8034 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8035 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8036 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8037 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8038 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8039 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8040 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8041 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8042 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8043 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8044 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8045 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8046 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8047 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8048 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8049 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8050 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8051 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8052 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8053 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8054 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8055 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8056 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8057 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8058 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8059 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8060 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8061 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8062 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8063 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8064 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8065 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8066 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8067 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8068 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8069 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8070 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8071 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8072 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8073 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8074 FOR GL-INT8 NO-DISPLAY.
SELECT-OPTIONS %%IN8075 FOR GL-INT8 NO-DISPLAY.

* UTCLONG, type 'p'
RANGES %%ULO001 FOR GL-ULO .
RANGES %%ULO002 FOR GL-ULO .
RANGES %%ULO003 FOR GL-ULO .
RANGES %%ULO004 FOR GL-ULO .
RANGES %%ULO005 FOR GL-ULO .
RANGES %%ULO006 FOR GL-ULO .
RANGES %%ULO007 FOR GL-ULO .
RANGES %%ULO008 FOR GL-ULO .
RANGES %%ULO009 FOR GL-ULO .
RANGES %%ULO010 FOR GL-ULO .
RANGES %%ULO011 FOR GL-ULO .
RANGES %%ULO012 FOR GL-ULO .
RANGES %%ULO013 FOR GL-ULO .
RANGES %%ULO014 FOR GL-ULO .
RANGES %%ULO015 FOR GL-ULO .
RANGES %%ULO016 FOR GL-ULO .
RANGES %%ULO017 FOR GL-ULO .
RANGES %%ULO018 FOR GL-ULO .
RANGES %%ULO019 FOR GL-ULO .
RANGES %%ULO020 FOR GL-ULO .
RANGES %%ULO021 FOR GL-ULO .
RANGES %%ULO022 FOR GL-ULO .
RANGES %%ULO023 FOR GL-ULO .
RANGES %%ULO024 FOR GL-ULO .
RANGES %%ULO025 FOR GL-ULO .
RANGES %%ULO026 FOR GL-ULO .
RANGES %%ULO027 FOR GL-ULO .
RANGES %%ULO028 FOR GL-ULO .
RANGES %%ULO029 FOR GL-ULO .
RANGES %%ULO030 FOR GL-ULO .
RANGES %%ULO031 FOR GL-ULO .
RANGES %%ULO032 FOR GL-ULO .
RANGES %%ULO033 FOR GL-ULO .
RANGES %%ULO034 FOR GL-ULO .
RANGES %%ULO035 FOR GL-ULO .
RANGES %%ULO036 FOR GL-ULO .
RANGES %%ULO037 FOR GL-ULO .
RANGES %%ULO038 FOR GL-ULO .
RANGES %%ULO039 FOR GL-ULO .
RANGES %%ULO040 FOR GL-ULO .
RANGES %%ULO041 FOR GL-ULO .
RANGES %%ULO042 FOR GL-ULO .
RANGES %%ULO043 FOR GL-ULO .
RANGES %%ULO044 FOR GL-ULO .
RANGES %%ULO045 FOR GL-ULO .
RANGES %%ULO046 FOR GL-ULO .
RANGES %%ULO047 FOR GL-ULO .
RANGES %%ULO048 FOR GL-ULO .
RANGES %%ULO049 FOR GL-ULO .
RANGES %%ULO050 FOR GL-ULO .
RANGES %%ULO051 FOR GL-ULO .
RANGES %%ULO052 FOR GL-ULO .
RANGES %%ULO053 FOR GL-ULO .
RANGES %%ULO054 FOR GL-ULO .
RANGES %%ULO055 FOR GL-ULO .
RANGES %%ULO056 FOR GL-ULO .
RANGES %%ULO057 FOR GL-ULO .
RANGES %%ULO058 FOR GL-ULO .
RANGES %%ULO059 FOR GL-ULO .
RANGES %%ULO060 FOR GL-ULO .
RANGES %%ULO061 FOR GL-ULO .
RANGES %%ULO062 FOR GL-ULO .
RANGES %%ULO063 FOR GL-ULO .
RANGES %%ULO064 FOR GL-ULO .
RANGES %%ULO065 FOR GL-ULO .
RANGES %%ULO066 FOR GL-ULO .
RANGES %%ULO067 FOR GL-ULO .
RANGES %%ULO068 FOR GL-ULO .
RANGES %%ULO069 FOR GL-ULO .
RANGES %%ULO070 FOR GL-ULO .
RANGES %%ULO071 FOR GL-ULO .
RANGES %%ULO072 FOR GL-ULO .
RANGES %%ULO073 FOR GL-ULO .
RANGES %%ULO074 FOR GL-ULO .
RANGES %%ULO075 FOR GL-ULO .

* Integers
SELECT-OPTIONS %%FLT001 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT002 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT003 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT004 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT005 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT006 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT007 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT008 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT009 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT010 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT011 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT012 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT013 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT014 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT015 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT016 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT017 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT018 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT019 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT020 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT021 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT022 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT023 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT024 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT025 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT026 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT027 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT028 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT029 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT030 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT031 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT032 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT033 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT034 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT035 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT036 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT037 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT038 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT039 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT040 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT041 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT042 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT043 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT044 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT045 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT046 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT047 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT048 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT049 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT050 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT051 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT052 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT053 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT054 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT055 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT056 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT057 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT058 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT059 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT060 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT061 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT062 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT063 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT064 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT065 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT066 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT067 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT068 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT069 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT070 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT071 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT072 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT073 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT074 FOR GL-FLOAT NO-DISPLAY.
SELECT-OPTIONS %%FLT075 FOR GL-FLOAT NO-DISPLAY.

* DECFLOAT 16
SELECT-OPTIONS %%DFA001 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA002 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA003 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA004 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA005 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA006 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA007 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA008 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA009 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA010 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA011 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA012 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA013 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA014 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA015 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA016 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA017 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA018 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA019 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA020 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA021 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA022 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA023 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA024 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA025 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA026 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA027 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA028 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA029 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA030 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA031 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA032 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA033 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA034 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA035 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA036 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA037 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA038 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA039 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA040 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA041 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA042 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA043 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA044 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA045 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA046 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA047 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA048 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA049 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA050 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA051 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA052 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA053 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA054 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA055 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA056 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA057 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA058 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA059 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA060 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA061 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA062 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA063 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA064 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA065 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA066 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA067 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA068 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA069 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA070 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA071 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA072 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA073 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA074 FOR GL-DECF_16 NO-DISPLAY.
SELECT-OPTIONS %%DFA075 FOR GL-DECF_16 NO-DISPLAY.

* DECFLOAT 34
SELECT-OPTIONS %%DFE001 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE002 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE003 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE004 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE005 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE006 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE007 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE008 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE009 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE010 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE011 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE012 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE013 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE014 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE015 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE016 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE017 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE018 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE019 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE020 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE021 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE022 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE023 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE024 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE025 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE026 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE027 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE028 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE029 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE030 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE031 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE032 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE033 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE034 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE035 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE036 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE037 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE038 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE039 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE040 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE041 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE042 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE043 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE044 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE045 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE046 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE047 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE048 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE049 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE050 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE051 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE052 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE053 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE054 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE055 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE056 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE057 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE058 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE059 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE060 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE061 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE062 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE063 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE064 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE065 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE066 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE067 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE068 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE069 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE070 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE071 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE072 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE073 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE074 FOR GL-DECF_34 NO-DISPLAY.
SELECT-OPTIONS %%DFE075 FOR GL-DECF_34 NO-DISPLAY.

* Sichtbare

SELECTION-SCREEN BEGIN OF BLOCK DYN.
SELECTION-SCREEN COMMENT /1(78) COMM%001 MODIF ID 901.
SELECT-OPTIONS %%DYN001 FOR RSDSINTERN-SELOPT MODIF ID 001.
SELECTION-SCREEN COMMENT /1(78) COMM%002 MODIF ID 902.
SELECT-OPTIONS %%DYN002 FOR RSDSINTERN-SELOPT MODIF ID 002.
SELECTION-SCREEN COMMENT /1(78) COMM%003 MODIF ID 903.
SELECT-OPTIONS %%DYN003 FOR RSDSINTERN-SELOPT MODIF ID 003.
SELECTION-SCREEN COMMENT /1(78) COMM%004 MODIF ID 904.
SELECT-OPTIONS %%DYN004 FOR RSDSINTERN-SELOPT MODIF ID 004.
SELECTION-SCREEN COMMENT /1(78) COMM%005 MODIF ID 905.
SELECT-OPTIONS %%DYN005 FOR RSDSINTERN-SELOPT MODIF ID 005.
SELECTION-SCREEN COMMENT /1(78) COMM%006 MODIF ID 906.
SELECT-OPTIONS %%DYN006 FOR RSDSINTERN-SELOPT MODIF ID 006.
SELECTION-SCREEN COMMENT /1(78) COMM%007 MODIF ID 907.
SELECT-OPTIONS %%DYN007 FOR RSDSINTERN-SELOPT MODIF ID 007.
SELECTION-SCREEN COMMENT /1(78) COMM%008 MODIF ID 908.
SELECT-OPTIONS %%DYN008 FOR RSDSINTERN-SELOPT MODIF ID 008.
SELECTION-SCREEN COMMENT /1(78) COMM%009 MODIF ID 909.
SELECT-OPTIONS %%DYN009 FOR RSDSINTERN-SELOPT MODIF ID 009.
SELECTION-SCREEN COMMENT /1(78) COMM%010 MODIF ID 910.
SELECT-OPTIONS %%DYN010 FOR RSDSINTERN-SELOPT MODIF ID 010.
SELECTION-SCREEN COMMENT /1(78) COMM%011 MODIF ID 911.
SELECT-OPTIONS %%DYN011 FOR RSDSINTERN-SELOPT MODIF ID 011.
SELECTION-SCREEN COMMENT /1(78) COMM%012 MODIF ID 912.
SELECT-OPTIONS %%DYN012 FOR RSDSINTERN-SELOPT MODIF ID 012.
SELECTION-SCREEN COMMENT /1(78) COMM%013 MODIF ID 913.
SELECT-OPTIONS %%DYN013 FOR RSDSINTERN-SELOPT MODIF ID 013.
SELECTION-SCREEN COMMENT /1(78) COMM%014 MODIF ID 914.
SELECT-OPTIONS %%DYN014 FOR RSDSINTERN-SELOPT MODIF ID 014.
SELECTION-SCREEN COMMENT /1(78) COMM%015 MODIF ID 915.
SELECT-OPTIONS %%DYN015 FOR RSDSINTERN-SELOPT MODIF ID 015.
SELECTION-SCREEN COMMENT /1(78) COMM%016 MODIF ID 916.
SELECT-OPTIONS %%DYN016 FOR RSDSINTERN-SELOPT MODIF ID 016.
SELECTION-SCREEN COMMENT /1(78) COMM%017 MODIF ID 917.
SELECT-OPTIONS %%DYN017 FOR RSDSINTERN-SELOPT MODIF ID 017.
SELECTION-SCREEN COMMENT /1(78) COMM%018 MODIF ID 918.
SELECT-OPTIONS %%DYN018 FOR RSDSINTERN-SELOPT MODIF ID 018.
SELECTION-SCREEN COMMENT /1(78) COMM%019 MODIF ID 919.
SELECT-OPTIONS %%DYN019 FOR RSDSINTERN-SELOPT MODIF ID 019.
SELECTION-SCREEN COMMENT /1(78) COMM%020 MODIF ID 920.
SELECT-OPTIONS %%DYN020 FOR RSDSINTERN-SELOPT MODIF ID 020.
SELECTION-SCREEN COMMENT /1(78) COMM%021 MODIF ID 921.
SELECT-OPTIONS %%DYN021 FOR RSDSINTERN-SELOPT MODIF ID 021.
SELECTION-SCREEN COMMENT /1(78) COMM%022 MODIF ID 922.
SELECT-OPTIONS %%DYN022 FOR RSDSINTERN-SELOPT MODIF ID 022.
SELECTION-SCREEN COMMENT /1(78) COMM%023 MODIF ID 923.
SELECT-OPTIONS %%DYN023 FOR RSDSINTERN-SELOPT MODIF ID 023.
SELECTION-SCREEN COMMENT /1(78) COMM%024 MODIF ID 924.
SELECT-OPTIONS %%DYN024 FOR RSDSINTERN-SELOPT MODIF ID 024.
SELECTION-SCREEN COMMENT /1(78) COMM%025 MODIF ID 925.
SELECT-OPTIONS %%DYN025 FOR RSDSINTERN-SELOPT MODIF ID 025.
SELECTION-SCREEN COMMENT /1(78) COMM%026 MODIF ID 926.
SELECT-OPTIONS %%DYN026 FOR RSDSINTERN-SELOPT MODIF ID 026.
SELECTION-SCREEN COMMENT /1(78) COMM%027 MODIF ID 927.
SELECT-OPTIONS %%DYN027 FOR RSDSINTERN-SELOPT MODIF ID 027.
SELECTION-SCREEN COMMENT /1(78) COMM%028 MODIF ID 928.
SELECT-OPTIONS %%DYN028 FOR RSDSINTERN-SELOPT MODIF ID 028.
SELECTION-SCREEN COMMENT /1(78) COMM%029 MODIF ID 929.
SELECT-OPTIONS %%DYN029 FOR RSDSINTERN-SELOPT MODIF ID 029.
SELECTION-SCREEN COMMENT /1(78) COMM%030 MODIF ID 930.
SELECT-OPTIONS %%DYN030 FOR RSDSINTERN-SELOPT MODIF ID 030.
SELECTION-SCREEN COMMENT /1(78) COMM%031 MODIF ID 931.
SELECT-OPTIONS %%DYN031 FOR RSDSINTERN-SELOPT MODIF ID 031.
SELECTION-SCREEN COMMENT /1(78) COMM%032 MODIF ID 932.
SELECT-OPTIONS %%DYN032 FOR RSDSINTERN-SELOPT MODIF ID 032.
SELECTION-SCREEN COMMENT /1(78) COMM%033 MODIF ID 933.
SELECT-OPTIONS %%DYN033 FOR RSDSINTERN-SELOPT MODIF ID 033.
SELECTION-SCREEN COMMENT /1(78) COMM%034 MODIF ID 934.
SELECT-OPTIONS %%DYN034 FOR RSDSINTERN-SELOPT MODIF ID 034.
SELECTION-SCREEN COMMENT /1(78) COMM%035 MODIF ID 935.
SELECT-OPTIONS %%DYN035 FOR RSDSINTERN-SELOPT MODIF ID 035.
SELECTION-SCREEN COMMENT /1(78) COMM%036 MODIF ID 936.
SELECT-OPTIONS %%DYN036 FOR RSDSINTERN-SELOPT MODIF ID 036.
SELECTION-SCREEN COMMENT /1(78) COMM%037 MODIF ID 937.
SELECT-OPTIONS %%DYN037 FOR RSDSINTERN-SELOPT MODIF ID 037.
SELECTION-SCREEN COMMENT /1(78) COMM%038 MODIF ID 938.
SELECT-OPTIONS %%DYN038 FOR RSDSINTERN-SELOPT MODIF ID 038.
SELECTION-SCREEN COMMENT /1(78) COMM%039 MODIF ID 939.
SELECT-OPTIONS %%DYN039 FOR RSDSINTERN-SELOPT MODIF ID 039.
SELECTION-SCREEN COMMENT /1(78) COMM%040 MODIF ID 940.
SELECT-OPTIONS %%DYN040 FOR RSDSINTERN-SELOPT MODIF ID 040.
SELECTION-SCREEN COMMENT /1(78) COMM%041 MODIF ID 941.
SELECT-OPTIONS %%DYN041 FOR RSDSINTERN-SELOPT MODIF ID 041.
SELECTION-SCREEN COMMENT /1(78) COMM%042 MODIF ID 942.
SELECT-OPTIONS %%DYN042 FOR RSDSINTERN-SELOPT MODIF ID 042.
SELECTION-SCREEN COMMENT /1(78) COMM%043 MODIF ID 943.
SELECT-OPTIONS %%DYN043 FOR RSDSINTERN-SELOPT MODIF ID 043.
SELECTION-SCREEN COMMENT /1(78) COMM%044 MODIF ID 944.
SELECT-OPTIONS %%DYN044 FOR RSDSINTERN-SELOPT MODIF ID 044.
SELECTION-SCREEN COMMENT /1(78) COMM%045 MODIF ID 945.
SELECT-OPTIONS %%DYN045 FOR RSDSINTERN-SELOPT MODIF ID 045.
SELECTION-SCREEN COMMENT /1(78) COMM%046 MODIF ID 946.
SELECT-OPTIONS %%DYN046 FOR RSDSINTERN-SELOPT MODIF ID 046.
SELECTION-SCREEN COMMENT /1(78) COMM%047 MODIF ID 947.
SELECT-OPTIONS %%DYN047 FOR RSDSINTERN-SELOPT MODIF ID 047.
SELECTION-SCREEN COMMENT /1(78) COMM%048 MODIF ID 948.
SELECT-OPTIONS %%DYN048 FOR RSDSINTERN-SELOPT MODIF ID 048.
SELECTION-SCREEN COMMENT /1(78) COMM%049 MODIF ID 949.
SELECT-OPTIONS %%DYN049 FOR RSDSINTERN-SELOPT MODIF ID 049.
SELECTION-SCREEN COMMENT /1(78) COMM%050 MODIF ID 950.
SELECT-OPTIONS %%DYN050 FOR RSDSINTERN-SELOPT MODIF ID 050.
SELECTION-SCREEN COMMENT /1(78) COMM%051 MODIF ID 951.
SELECT-OPTIONS %%DYN051 FOR RSDSINTERN-SELOPT MODIF ID 051.
SELECTION-SCREEN COMMENT /1(78) COMM%052 MODIF ID 952.
SELECT-OPTIONS %%DYN052 FOR RSDSINTERN-SELOPT MODIF ID 052.
SELECTION-SCREEN COMMENT /1(78) COMM%053 MODIF ID 953.
SELECT-OPTIONS %%DYN053 FOR RSDSINTERN-SELOPT MODIF ID 053.
SELECTION-SCREEN COMMENT /1(78) COMM%054 MODIF ID 954.
SELECT-OPTIONS %%DYN054 FOR RSDSINTERN-SELOPT MODIF ID 054.
SELECTION-SCREEN COMMENT /1(78) COMM%055 MODIF ID 955.
SELECT-OPTIONS %%DYN055 FOR RSDSINTERN-SELOPT MODIF ID 055.
SELECTION-SCREEN COMMENT /1(78) COMM%056 MODIF ID 956.
SELECT-OPTIONS %%DYN056 FOR RSDSINTERN-SELOPT MODIF ID 056.
SELECTION-SCREEN COMMENT /1(78) COMM%057 MODIF ID 957.
SELECT-OPTIONS %%DYN057 FOR RSDSINTERN-SELOPT MODIF ID 057.
SELECTION-SCREEN COMMENT /1(78) COMM%058 MODIF ID 958.
SELECT-OPTIONS %%DYN058 FOR RSDSINTERN-SELOPT MODIF ID 058.
SELECTION-SCREEN COMMENT /1(78) COMM%059 MODIF ID 959.
SELECT-OPTIONS %%DYN059 FOR RSDSINTERN-SELOPT MODIF ID 059.
SELECTION-SCREEN COMMENT /1(78) COMM%060 MODIF ID 960.
SELECT-OPTIONS %%DYN060 FOR RSDSINTERN-SELOPT MODIF ID 060.
SELECTION-SCREEN COMMENT /1(78) COMM%061 MODIF ID 961.
SELECT-OPTIONS %%DYN061 FOR RSDSINTERN-SELOPT MODIF ID 061.
SELECTION-SCREEN COMMENT /1(78) COMM%062 MODIF ID 962.
SELECT-OPTIONS %%DYN062 FOR RSDSINTERN-SELOPT MODIF ID 062.
SELECTION-SCREEN COMMENT /1(78) COMM%063 MODIF ID 963.
SELECT-OPTIONS %%DYN063 FOR RSDSINTERN-SELOPT MODIF ID 063.
SELECTION-SCREEN COMMENT /1(78) COMM%064 MODIF ID 964.
SELECT-OPTIONS %%DYN064 FOR RSDSINTERN-SELOPT MODIF ID 064.
SELECTION-SCREEN COMMENT /1(78) COMM%065 MODIF ID 965.
SELECT-OPTIONS %%DYN065 FOR RSDSINTERN-SELOPT MODIF ID 065.
SELECTION-SCREEN COMMENT /1(78) COMM%066 MODIF ID 966.
SELECT-OPTIONS %%DYN066 FOR RSDSINTERN-SELOPT MODIF ID 066.
SELECTION-SCREEN COMMENT /1(78) COMM%067 MODIF ID 967.
SELECT-OPTIONS %%DYN067 FOR RSDSINTERN-SELOPT MODIF ID 067.
SELECTION-SCREEN COMMENT /1(78) COMM%068 MODIF ID 968.
SELECT-OPTIONS %%DYN068 FOR RSDSINTERN-SELOPT MODIF ID 068.
SELECTION-SCREEN COMMENT /1(78) COMM%069 MODIF ID 969.
SELECT-OPTIONS %%DYN069 FOR RSDSINTERN-SELOPT MODIF ID 069.
SELECTION-SCREEN COMMENT /1(78) COMM%070 MODIF ID 970.
SELECT-OPTIONS %%DYN070 FOR RSDSINTERN-SELOPT MODIF ID 070.
SELECTION-SCREEN COMMENT /1(78) COMM%071 MODIF ID 971.
SELECT-OPTIONS %%DYN071 FOR RSDSINTERN-SELOPT MODIF ID 071.
SELECTION-SCREEN COMMENT /1(78) COMM%072 MODIF ID 972.
SELECT-OPTIONS %%DYN072 FOR RSDSINTERN-SELOPT MODIF ID 072.
SELECTION-SCREEN COMMENT /1(78) COMM%073 MODIF ID 973.
SELECT-OPTIONS %%DYN073 FOR RSDSINTERN-SELOPT MODIF ID 073.
SELECTION-SCREEN COMMENT /1(78) COMM%074 MODIF ID 974.
SELECT-OPTIONS %%DYN074 FOR RSDSINTERN-SELOPT MODIF ID 074.
SELECTION-SCREEN COMMENT /1(78) COMM%075 MODIF ID 975.
SELECT-OPTIONS %%DYN075 FOR RSDSINTERN-SELOPT MODIF ID 075.
SELECTION-SCREEN END   OF BLOCK DYN.
