***INCLUDE RSDYNSC1.

AT SELECTION-SCREEN ON %%DYN001.
  PERFORM AT_SEL_ON USING %%DYN001 '001'.
AT SELECTION-SCREEN ON %%DYN002.
  PERFORM AT_SEL_ON USING %%DYN002 '002'.
AT SELECTION-SCREEN ON %%DYN003.
  PERFORM AT_SEL_ON USING %%DYN003 '003'.
AT SELECTION-SCREEN ON %%DYN004.
  PERFORM AT_SEL_ON USING %%DYN004 '004'.
AT SELECTION-SCREEN ON %%DYN005.
  PERFORM AT_SEL_ON USING %%DYN005 '005'.
AT SELECTION-SCREEN ON %%DYN006.
  PERFORM AT_SEL_ON USING %%DYN006 '006'.
AT SELECTION-SCREEN ON %%DYN007.
  PERFORM AT_SEL_ON USING %%DYN007 '007'.
AT SELECTION-SCREEN ON %%DYN008.
  PERFORM AT_SEL_ON USING %%DYN008 '008'.
AT SELECTION-SCREEN ON %%DYN009.
  PERFORM AT_SEL_ON USING %%DYN009 '009'.
AT SELECTION-SCREEN ON %%DYN010.
  PERFORM AT_SEL_ON USING %%DYN010 '010'.
AT SELECTION-SCREEN ON %%DYN011.
  PERFORM AT_SEL_ON USING %%DYN011 '011'.
AT SELECTION-SCREEN ON %%DYN012.
  PERFORM AT_SEL_ON USING %%DYN012 '012'.
AT SELECTION-SCREEN ON %%DYN013.
  PERFORM AT_SEL_ON USING %%DYN013 '013'.
AT SELECTION-SCREEN ON %%DYN014.
  PERFORM AT_SEL_ON USING %%DYN014 '014'.
AT SELECTION-SCREEN ON %%DYN015.
  PERFORM AT_SEL_ON USING %%DYN015 '015'.
AT SELECTION-SCREEN ON %%DYN016.
  PERFORM AT_SEL_ON USING %%DYN016 '016'.
AT SELECTION-SCREEN ON %%DYN017.
  PERFORM AT_SEL_ON USING %%DYN017 '017'.
AT SELECTION-SCREEN ON %%DYN018.
  PERFORM AT_SEL_ON USING %%DYN018 '018'.
AT SELECTION-SCREEN ON %%DYN019.
  PERFORM AT_SEL_ON USING %%DYN019 '019'.
AT SELECTION-SCREEN ON %%DYN020.
  PERFORM AT_SEL_ON USING %%DYN020 '020'.
AT SELECTION-SCREEN ON %%DYN021.
  PERFORM AT_SEL_ON USING %%DYN021 '021'.
AT SELECTION-SCREEN ON %%DYN022.
  PERFORM AT_SEL_ON USING %%DYN022 '022'.
AT SELECTION-SCREEN ON %%DYN023.
  PERFORM AT_SEL_ON USING %%DYN023 '023'.
AT SELECTION-SCREEN ON %%DYN024.
  PERFORM AT_SEL_ON USING %%DYN024 '024'.
AT SELECTION-SCREEN ON %%DYN025.
  PERFORM AT_SEL_ON USING %%DYN025 '025'.
AT SELECTION-SCREEN ON %%DYN026.
  PERFORM AT_SEL_ON USING %%DYN026 '026'.
AT SELECTION-SCREEN ON %%DYN027.
  PERFORM AT_SEL_ON USING %%DYN027 '027'.
AT SELECTION-SCREEN ON %%DYN028.
  PERFORM AT_SEL_ON USING %%DYN028 '028'.
AT SELECTION-SCREEN ON %%DYN029.
  PERFORM AT_SEL_ON USING %%DYN029 '029'.
AT SELECTION-SCREEN ON %%DYN030.
  PERFORM AT_SEL_ON USING %%DYN030 '030'.
AT SELECTION-SCREEN ON %%DYN031.
  PERFORM AT_SEL_ON USING %%DYN031 '031'.
AT SELECTION-SCREEN ON %%DYN032.
  PERFORM AT_SEL_ON USING %%DYN032 '032'.
AT SELECTION-SCREEN ON %%DYN033.
  PERFORM AT_SEL_ON USING %%DYN033 '033'.
AT SELECTION-SCREEN ON %%DYN034.
  PERFORM AT_SEL_ON USING %%DYN034 '034'.
AT SELECTION-SCREEN ON %%DYN035.
  PERFORM AT_SEL_ON USING %%DYN035 '035'.
AT SELECTION-SCREEN ON %%DYN036.
  PERFORM AT_SEL_ON USING %%DYN036 '036'.
AT SELECTION-SCREEN ON %%DYN037.
  PERFORM AT_SEL_ON USING %%DYN037 '037'.
AT SELECTION-SCREEN ON %%DYN038.
  PERFORM AT_SEL_ON USING %%DYN038 '038'.
AT SELECTION-SCREEN ON %%DYN039.
  PERFORM AT_SEL_ON USING %%DYN039 '039'.
AT SELECTION-SCREEN ON %%DYN040.
  PERFORM AT_SEL_ON USING %%DYN040 '040'.
AT SELECTION-SCREEN ON %%DYN041.
  PERFORM AT_SEL_ON USING %%DYN041 '041'.
AT SELECTION-SCREEN ON %%DYN042.
  PERFORM AT_SEL_ON USING %%DYN042 '042'.
AT SELECTION-SCREEN ON %%DYN043.
  PERFORM AT_SEL_ON USING %%DYN043 '043'.
AT SELECTION-SCREEN ON %%DYN044.
  PERFORM AT_SEL_ON USING %%DYN044 '044'.
AT SELECTION-SCREEN ON %%DYN045.
  PERFORM AT_SEL_ON USING %%DYN045 '045'.
AT SELECTION-SCREEN ON %%DYN046.
  PERFORM AT_SEL_ON USING %%DYN046 '046'.
AT SELECTION-SCREEN ON %%DYN047.
  PERFORM AT_SEL_ON USING %%DYN047 '047'.
AT SELECTION-SCREEN ON %%DYN048.
  PERFORM AT_SEL_ON USING %%DYN048 '048'.
AT SELECTION-SCREEN ON %%DYN049.
  PERFORM AT_SEL_ON USING %%DYN049 '049'.
AT SELECTION-SCREEN ON %%DYN050.
  PERFORM AT_SEL_ON USING %%DYN050 '050'.
AT SELECTION-SCREEN ON %%DYN051.
  PERFORM AT_SEL_ON USING %%DYN051 '051'.
AT SELECTION-SCREEN ON %%DYN052.
  PERFORM AT_SEL_ON USING %%DYN052 '052'.
AT SELECTION-SCREEN ON %%DYN053.
  PERFORM AT_SEL_ON USING %%DYN053 '053'.
AT SELECTION-SCREEN ON %%DYN054.
  PERFORM AT_SEL_ON USING %%DYN054 '054'.
AT SELECTION-SCREEN ON %%DYN055.
  PERFORM AT_SEL_ON USING %%DYN055 '055'.
AT SELECTION-SCREEN ON %%DYN056.
  PERFORM AT_SEL_ON USING %%DYN056 '056'.
AT SELECTION-SCREEN ON %%DYN057.
  PERFORM AT_SEL_ON USING %%DYN057 '057'.
AT SELECTION-SCREEN ON %%DYN058.
  PERFORM AT_SEL_ON USING %%DYN058 '058'.
AT SELECTION-SCREEN ON %%DYN059.
  PERFORM AT_SEL_ON USING %%DYN059 '059'.
AT SELECTION-SCREEN ON %%DYN060.
  PERFORM AT_SEL_ON USING %%DYN060 '060'.
AT SELECTION-SCREEN ON %%DYN061.
  PERFORM AT_SEL_ON USING %%DYN061 '061'.
AT SELECTION-SCREEN ON %%DYN062.
  PERFORM AT_SEL_ON USING %%DYN062 '062'.
AT SELECTION-SCREEN ON %%DYN063.
  PERFORM AT_SEL_ON USING %%DYN063 '063'.
AT SELECTION-SCREEN ON %%DYN064.
  PERFORM AT_SEL_ON USING %%DYN064 '064'.
AT SELECTION-SCREEN ON %%DYN065.
  PERFORM AT_SEL_ON USING %%DYN065 '065'.
AT SELECTION-SCREEN ON %%DYN066.
  PERFORM AT_SEL_ON USING %%DYN066 '066'.
AT SELECTION-SCREEN ON %%DYN067.
  PERFORM AT_SEL_ON USING %%DYN067 '067'.
AT SELECTION-SCREEN ON %%DYN068.
  PERFORM AT_SEL_ON USING %%DYN068 '068'.
AT SELECTION-SCREEN ON %%DYN069.
  PERFORM AT_SEL_ON USING %%DYN069 '069'.
AT SELECTION-SCREEN ON %%DYN070.
  PERFORM AT_SEL_ON USING %%DYN070 '070'.
AT SELECTION-SCREEN ON %%DYN071.
  PERFORM AT_SEL_ON USING %%DYN071 '071'.
AT SELECTION-SCREEN ON %%DYN072.
  PERFORM AT_SEL_ON USING %%DYN072 '072'.
AT SELECTION-SCREEN ON %%DYN073.
  PERFORM AT_SEL_ON USING %%DYN073 '073'.
AT SELECTION-SCREEN ON %%DYN074.
  PERFORM AT_SEL_ON USING %%DYN074 '074'.
AT SELECTION-SCREEN ON %%DYN075.
  PERFORM AT_SEL_ON USING %%DYN075 '075'.

AT SELECTION-SCREEN ON END OF %%DYN001.
  PERFORM AT_SEL_ON_END USING %%DYN001 '001'.
AT SELECTION-SCREEN ON END OF %%DYN002.
  PERFORM AT_SEL_ON_END USING %%DYN002 '002'.
AT SELECTION-SCREEN ON END OF %%DYN003.
  PERFORM AT_SEL_ON_END USING %%DYN003 '003'.
AT SELECTION-SCREEN ON END OF %%DYN004.
  PERFORM AT_SEL_ON_END USING %%DYN004 '004'.
AT SELECTION-SCREEN ON END OF %%DYN005.
  PERFORM AT_SEL_ON_END USING %%DYN005 '005'.
AT SELECTION-SCREEN ON END OF %%DYN006.
  PERFORM AT_SEL_ON_END USING %%DYN006 '006'.
AT SELECTION-SCREEN ON END OF %%DYN007.
  PERFORM AT_SEL_ON_END USING %%DYN007 '007'.
AT SELECTION-SCREEN ON END OF %%DYN008.
  PERFORM AT_SEL_ON_END USING %%DYN008 '008'.
AT SELECTION-SCREEN ON END OF %%DYN009.
  PERFORM AT_SEL_ON_END USING %%DYN009 '009'.
AT SELECTION-SCREEN ON END OF %%DYN010.
  PERFORM AT_SEL_ON_END USING %%DYN010 '010'.
AT SELECTION-SCREEN ON END OF %%DYN011.
  PERFORM AT_SEL_ON_END USING %%DYN011 '011'.
AT SELECTION-SCREEN ON END OF %%DYN012.
  PERFORM AT_SEL_ON_END USING %%DYN012 '012'.
AT SELECTION-SCREEN ON END OF %%DYN013.
  PERFORM AT_SEL_ON_END USING %%DYN013 '013'.
AT SELECTION-SCREEN ON END OF %%DYN014.
  PERFORM AT_SEL_ON_END USING %%DYN014 '014'.
AT SELECTION-SCREEN ON END OF %%DYN015.
  PERFORM AT_SEL_ON_END USING %%DYN015 '015'.
AT SELECTION-SCREEN ON END OF %%DYN016.
  PERFORM AT_SEL_ON_END USING %%DYN016 '016'.
AT SELECTION-SCREEN ON END OF %%DYN017.
  PERFORM AT_SEL_ON_END USING %%DYN017 '017'.
AT SELECTION-SCREEN ON END OF %%DYN018.
  PERFORM AT_SEL_ON_END USING %%DYN018 '018'.
AT SELECTION-SCREEN ON END OF %%DYN019.
  PERFORM AT_SEL_ON_END USING %%DYN019 '019'.
AT SELECTION-SCREEN ON END OF %%DYN020.
  PERFORM AT_SEL_ON_END USING %%DYN020 '020'.
AT SELECTION-SCREEN ON END OF %%DYN021.
  PERFORM AT_SEL_ON_END USING %%DYN021 '021'.
AT SELECTION-SCREEN ON END OF %%DYN022.
  PERFORM AT_SEL_ON_END USING %%DYN022 '022'.
AT SELECTION-SCREEN ON END OF %%DYN023.
  PERFORM AT_SEL_ON_END USING %%DYN023 '023'.
AT SELECTION-SCREEN ON END OF %%DYN024.
  PERFORM AT_SEL_ON_END USING %%DYN024 '024'.
AT SELECTION-SCREEN ON END OF %%DYN025.
  PERFORM AT_SEL_ON_END USING %%DYN025 '025'.
AT SELECTION-SCREEN ON END OF %%DYN026.
  PERFORM AT_SEL_ON_END USING %%DYN026 '026'.
AT SELECTION-SCREEN ON END OF %%DYN027.
  PERFORM AT_SEL_ON_END USING %%DYN027 '027'.
AT SELECTION-SCREEN ON END OF %%DYN028.
  PERFORM AT_SEL_ON_END USING %%DYN028 '028'.
AT SELECTION-SCREEN ON END OF %%DYN029.
  PERFORM AT_SEL_ON_END USING %%DYN029 '029'.
AT SELECTION-SCREEN ON END OF %%DYN030.
  PERFORM AT_SEL_ON_END USING %%DYN030 '030'.
AT SELECTION-SCREEN ON END OF %%DYN031.
  PERFORM AT_SEL_ON_END USING %%DYN031 '031'.
AT SELECTION-SCREEN ON END OF %%DYN032.
  PERFORM AT_SEL_ON_END USING %%DYN032 '032'.
AT SELECTION-SCREEN ON END OF %%DYN033.
  PERFORM AT_SEL_ON_END USING %%DYN033 '033'.
AT SELECTION-SCREEN ON END OF %%DYN034.
  PERFORM AT_SEL_ON_END USING %%DYN034 '034'.
AT SELECTION-SCREEN ON END OF %%DYN035.
  PERFORM AT_SEL_ON_END USING %%DYN035 '035'.
AT SELECTION-SCREEN ON END OF %%DYN036.
  PERFORM AT_SEL_ON_END USING %%DYN036 '036'.
AT SELECTION-SCREEN ON END OF %%DYN037.
  PERFORM AT_SEL_ON_END USING %%DYN037 '037'.
AT SELECTION-SCREEN ON END OF %%DYN038.
  PERFORM AT_SEL_ON_END USING %%DYN038 '038'.
AT SELECTION-SCREEN ON END OF %%DYN039.
  PERFORM AT_SEL_ON_END USING %%DYN039 '039'.
AT SELECTION-SCREEN ON END OF %%DYN040.
  PERFORM AT_SEL_ON_END USING %%DYN040 '040'.
AT SELECTION-SCREEN ON END OF %%DYN041.
  PERFORM AT_SEL_ON_END USING %%DYN041 '041'.
AT SELECTION-SCREEN ON END OF %%DYN042.
  PERFORM AT_SEL_ON_END USING %%DYN042 '042'.
AT SELECTION-SCREEN ON END OF %%DYN043.
  PERFORM AT_SEL_ON_END USING %%DYN043 '043'.
AT SELECTION-SCREEN ON END OF %%DYN044.
  PERFORM AT_SEL_ON_END USING %%DYN044 '044'.
AT SELECTION-SCREEN ON END OF %%DYN045.
  PERFORM AT_SEL_ON_END USING %%DYN045 '045'.
AT SELECTION-SCREEN ON END OF %%DYN046.
  PERFORM AT_SEL_ON_END USING %%DYN046 '046'.
AT SELECTION-SCREEN ON END OF %%DYN047.
  PERFORM AT_SEL_ON_END USING %%DYN047 '047'.
AT SELECTION-SCREEN ON END OF %%DYN048.
  PERFORM AT_SEL_ON_END USING %%DYN048 '048'.
AT SELECTION-SCREEN ON END OF %%DYN049.
  PERFORM AT_SEL_ON_END USING %%DYN049 '049'.
AT SELECTION-SCREEN ON END OF %%DYN050.
  PERFORM AT_SEL_ON_END USING %%DYN050 '050'.
AT SELECTION-SCREEN ON END OF %%DYN051.
  PERFORM AT_SEL_ON_END USING %%DYN051 '051'.
AT SELECTION-SCREEN ON END OF %%DYN052.
  PERFORM AT_SEL_ON_END USING %%DYN052 '052'.
AT SELECTION-SCREEN ON END OF %%DYN053.
  PERFORM AT_SEL_ON_END USING %%DYN053 '053'.
AT SELECTION-SCREEN ON END OF %%DYN054.
  PERFORM AT_SEL_ON_END USING %%DYN054 '054'.
AT SELECTION-SCREEN ON END OF %%DYN055.
  PERFORM AT_SEL_ON_END USING %%DYN055 '055'.
AT SELECTION-SCREEN ON END OF %%DYN056.
  PERFORM AT_SEL_ON_END USING %%DYN056 '056'.
AT SELECTION-SCREEN ON END OF %%DYN057.
  PERFORM AT_SEL_ON_END USING %%DYN057 '057'.
AT SELECTION-SCREEN ON END OF %%DYN058.
  PERFORM AT_SEL_ON_END USING %%DYN058 '058'.
AT SELECTION-SCREEN ON END OF %%DYN059.
  PERFORM AT_SEL_ON_END USING %%DYN059 '059'.
AT SELECTION-SCREEN ON END OF %%DYN060.
  PERFORM AT_SEL_ON_END USING %%DYN060 '060'.
AT SELECTION-SCREEN ON END OF %%DYN061.
  PERFORM AT_SEL_ON_END USING %%DYN061 '061'.
AT SELECTION-SCREEN ON END OF %%DYN062.
  PERFORM AT_SEL_ON_END USING %%DYN062 '062'.
AT SELECTION-SCREEN ON END OF %%DYN063.
  PERFORM AT_SEL_ON_END USING %%DYN063 '063'.
AT SELECTION-SCREEN ON END OF %%DYN064.
  PERFORM AT_SEL_ON_END USING %%DYN064 '064'.
AT SELECTION-SCREEN ON END OF %%DYN065.
  PERFORM AT_SEL_ON_END USING %%DYN065 '065'.
AT SELECTION-SCREEN ON END OF %%DYN066.
  PERFORM AT_SEL_ON_END USING %%DYN066 '066'.
AT SELECTION-SCREEN ON END OF %%DYN067.
  PERFORM AT_SEL_ON_END USING %%DYN067 '067'.
AT SELECTION-SCREEN ON END OF %%DYN068.
  PERFORM AT_SEL_ON_END USING %%DYN068 '068'.
AT SELECTION-SCREEN ON END OF %%DYN069.
  PERFORM AT_SEL_ON_END USING %%DYN069 '069'.
AT SELECTION-SCREEN ON END OF %%DYN070.
  PERFORM AT_SEL_ON_END USING %%DYN070 '070'.
AT SELECTION-SCREEN ON END OF %%DYN071.
  PERFORM AT_SEL_ON_END USING %%DYN071 '071'.
AT SELECTION-SCREEN ON END OF %%DYN072.
  PERFORM AT_SEL_ON_END USING %%DYN072 '072'.
AT SELECTION-SCREEN ON END OF %%DYN073.
  PERFORM AT_SEL_ON_END USING %%DYN073 '073'.
AT SELECTION-SCREEN ON END OF %%DYN074.
  PERFORM AT_SEL_ON_END USING %%DYN074 '074'.
AT SELECTION-SCREEN ON END OF %%DYN075.
  PERFORM AT_SEL_ON_END USING %%DYN075 '075'.

AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN001.
  PERFORM AT_SEL_ON_HLP USING '001'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN002.
  PERFORM AT_SEL_ON_HLP USING '002'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN003.
  PERFORM AT_SEL_ON_HLP USING '003'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN004.
  PERFORM AT_SEL_ON_HLP USING '004'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN005.
  PERFORM AT_SEL_ON_HLP USING '005'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN006.
  PERFORM AT_SEL_ON_HLP USING '006'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN007.
  PERFORM AT_SEL_ON_HLP USING '007'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN008.
  PERFORM AT_SEL_ON_HLP USING '008'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN009.
  PERFORM AT_SEL_ON_HLP USING '009'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN010.
  PERFORM AT_SEL_ON_HLP USING '010'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN011.
  PERFORM AT_SEL_ON_HLP USING '011'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN012.
  PERFORM AT_SEL_ON_HLP USING '012'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN013.
  PERFORM AT_SEL_ON_HLP USING '013'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN014.
  PERFORM AT_SEL_ON_HLP USING '014'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN015.
  PERFORM AT_SEL_ON_HLP USING '015'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN016.
  PERFORM AT_SEL_ON_HLP USING '016'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN017.
  PERFORM AT_SEL_ON_HLP USING '017'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN018.
  PERFORM AT_SEL_ON_HLP USING '018'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN019.
  PERFORM AT_SEL_ON_HLP USING '019'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN020.
  PERFORM AT_SEL_ON_HLP USING '020'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN021.
  PERFORM AT_SEL_ON_HLP USING '021'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN022.
  PERFORM AT_SEL_ON_HLP USING '022'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN023.
  PERFORM AT_SEL_ON_HLP USING '023'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN024.
  PERFORM AT_SEL_ON_HLP USING '024'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN025.
  PERFORM AT_SEL_ON_HLP USING '025'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN026.
  PERFORM AT_SEL_ON_HLP USING '026'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN027.
  PERFORM AT_SEL_ON_HLP USING '027'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN028.
  PERFORM AT_SEL_ON_HLP USING '028'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN029.
  PERFORM AT_SEL_ON_HLP USING '029'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN030.
  PERFORM AT_SEL_ON_HLP USING '030'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN031.
  PERFORM AT_SEL_ON_HLP USING '031'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN032.
  PERFORM AT_SEL_ON_HLP USING '032'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN033.
  PERFORM AT_SEL_ON_HLP USING '033'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN034.
  PERFORM AT_SEL_ON_HLP USING '034'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN035.
  PERFORM AT_SEL_ON_HLP USING '035'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN036.
  PERFORM AT_SEL_ON_HLP USING '036'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN037.
  PERFORM AT_SEL_ON_HLP USING '037'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN038.
  PERFORM AT_SEL_ON_HLP USING '038'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN039.
  PERFORM AT_SEL_ON_HLP USING '039'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN040.
  PERFORM AT_SEL_ON_HLP USING '040'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN041.
  PERFORM AT_SEL_ON_HLP USING '041'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN042.
  PERFORM AT_SEL_ON_HLP USING '042'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN043.
  PERFORM AT_SEL_ON_HLP USING '043'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN044.
  PERFORM AT_SEL_ON_HLP USING '044'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN045.
  PERFORM AT_SEL_ON_HLP USING '045'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN046.
  PERFORM AT_SEL_ON_HLP USING '046'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN047.
  PERFORM AT_SEL_ON_HLP USING '047'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN048.
  PERFORM AT_SEL_ON_HLP USING '048'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN049.
  PERFORM AT_SEL_ON_HLP USING '049'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN050.
  PERFORM AT_SEL_ON_HLP USING '050'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN051.
  PERFORM AT_SEL_ON_HLP USING '051'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN052.
  PERFORM AT_SEL_ON_HLP USING '052'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN053.
  PERFORM AT_SEL_ON_HLP USING '053'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN054.
  PERFORM AT_SEL_ON_HLP USING '054'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN055.
  PERFORM AT_SEL_ON_HLP USING '055'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN056.
  PERFORM AT_SEL_ON_HLP USING '056'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN057.
  PERFORM AT_SEL_ON_HLP USING '057'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN058.
  PERFORM AT_SEL_ON_HLP USING '058'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN059.
  PERFORM AT_SEL_ON_HLP USING '059'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN060.
  PERFORM AT_SEL_ON_HLP USING '060'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN061.
  PERFORM AT_SEL_ON_HLP USING '061'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN062.
  PERFORM AT_SEL_ON_HLP USING '062'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN063.
  PERFORM AT_SEL_ON_HLP USING '063'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN064.
  PERFORM AT_SEL_ON_HLP USING '064'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN065.
  PERFORM AT_SEL_ON_HLP USING '065'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN066.
  PERFORM AT_SEL_ON_HLP USING '066'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN067.
  PERFORM AT_SEL_ON_HLP USING '067'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN068.
  PERFORM AT_SEL_ON_HLP USING '068'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN069.
  PERFORM AT_SEL_ON_HLP USING '069'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN070.
  PERFORM AT_SEL_ON_HLP USING '070'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN071.
  PERFORM AT_SEL_ON_HLP USING '071'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN072.
  PERFORM AT_SEL_ON_HLP USING '072'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN073.
  PERFORM AT_SEL_ON_HLP USING '073'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN074.
  PERFORM AT_SEL_ON_HLP USING '074'.
AT SELECTION-SCREEN ON HELP-REQUEST FOR %%DYN075.
  PERFORM AT_SEL_ON_HLP USING '075'.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN001-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN001-LOW '001'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN002-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN002-LOW '002'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN003-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN003-LOW '003'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN004-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN004-LOW '004'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN005-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN005-LOW '005'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN006-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN006-LOW '006'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN007-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN007-LOW '007'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN008-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN008-LOW '008'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN009-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN009-LOW '009'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN010-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN010-LOW '010'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN011-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN011-LOW '011'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN012-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN012-LOW '012'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN013-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN013-LOW '013'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN014-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN014-LOW '014'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN015-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN015-LOW '015'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN016-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN016-LOW '016'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN017-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN017-LOW '017'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN018-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN018-LOW '018'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN019-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN019-LOW '019'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN020-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN020-LOW '020'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN021-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN021-LOW '021'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN022-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN022-LOW '022'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN023-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN023-LOW '023'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN024-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN024-LOW '024'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN025-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN025-LOW '025'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN026-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN026-LOW '026'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN027-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN027-LOW '027'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN028-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN028-LOW '028'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN029-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN029-LOW '029'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN030-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN030-LOW '030'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN031-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN031-LOW '031'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN032-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN032-LOW '032'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN033-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN033-LOW '033'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN034-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN034-LOW '034'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN035-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN035-LOW '035'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN036-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN036-LOW '036'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN037-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN037-LOW '037'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN038-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN038-LOW '038'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN039-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN039-LOW '039'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN040-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN040-LOW '040'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN041-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN041-LOW '041'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN042-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN042-LOW '042'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN043-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN043-LOW '043'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN044-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN044-LOW '044'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN045-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN045-LOW '045'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN046-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN046-LOW '046'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN047-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN047-LOW '047'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN048-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN048-LOW '048'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN049-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN049-LOW '049'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN050-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN050-LOW '050'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN051-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN051-LOW '051'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN052-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN052-LOW '052'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN053-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN053-LOW '053'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN054-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN054-LOW '054'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN055-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN055-LOW '055'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN056-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN056-LOW '056'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN057-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN057-LOW '057'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN058-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN058-LOW '058'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN059-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN059-LOW '059'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN060-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN060-LOW '060'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN061-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN061-LOW '061'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN062-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN062-LOW '062'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN063-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN063-LOW '063'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN064-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN064-LOW '064'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN065-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN065-LOW '065'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN066-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN066-LOW '066'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN067-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN067-LOW '067'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN068-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN068-LOW '068'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN069-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN069-LOW '069'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN070-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN070-LOW '070'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN071-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN071-LOW '071'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN072-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN072-LOW '072'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN073-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN073-LOW '073'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN074-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN074-LOW '074'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN075-LOW.
  PERFORM AT_SEL_ON_VAL USING 'LOW' %%DYN075-LOW '075'.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN001-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN001-HIGH '001'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN002-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN002-HIGH '002'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN003-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN003-HIGH '003'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN004-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN004-HIGH '004'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN005-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN005-HIGH '005'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN006-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN006-HIGH '006'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN007-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN007-HIGH '007'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN008-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN008-HIGH '008'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN009-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN009-HIGH '009'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN010-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN010-HIGH '010'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN011-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN011-HIGH '011'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN012-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN012-HIGH '012'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN013-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN013-HIGH '013'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN014-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN014-HIGH '014'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN015-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN015-HIGH '015'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN016-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN016-HIGH '016'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN017-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN017-HIGH '017'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN018-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN018-HIGH '018'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN019-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN019-HIGH '019'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN020-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN020-HIGH '020'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN021-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN021-HIGH '021'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN022-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN022-HIGH '022'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN023-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN023-HIGH '023'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN024-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN024-HIGH '024'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN025-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN025-HIGH '025'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN026-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN026-HIGH '026'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN027-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN027-HIGH '027'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN028-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN028-HIGH '028'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN029-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN029-HIGH '029'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN030-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN030-HIGH '030'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN031-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN031-HIGH '031'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN032-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN032-HIGH '032'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN033-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN033-HIGH '033'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN034-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN034-HIGH '034'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN035-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN035-HIGH '035'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN036-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN036-HIGH '036'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN037-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN037-HIGH '037'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN038-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN038-HIGH '038'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN039-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN039-HIGH '039'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN040-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN040-HIGH '040'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN041-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN041-HIGH '041'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN042-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN042-HIGH '042'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN043-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN043-HIGH '043'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN044-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN044-HIGH '044'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN045-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN045-HIGH '045'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN046-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN046-HIGH '046'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN047-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN047-HIGH '047'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN048-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN048-HIGH '048'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN049-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN049-HIGH '049'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN050-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN050-HIGH '050'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN051-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN051-HIGH '051'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN052-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN052-HIGH '052'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN053-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN053-HIGH '053'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN054-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN054-HIGH '054'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN055-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN055-HIGH '055'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN056-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN056-HIGH '056'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN057-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN057-HIGH '057'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN058-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN058-HIGH '058'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN059-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN059-HIGH '059'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN060-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN060-HIGH '060'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN061-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN061-HIGH '061'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN062-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN062-HIGH '062'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN063-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN063-HIGH '063'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN064-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN064-HIGH '064'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN065-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN065-HIGH '065'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN066-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN066-HIGH '066'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN067-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN067-HIGH '067'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN068-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN068-HIGH '068'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN069-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN069-HIGH '069'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN070-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN070-HIGH '070'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN071-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN071-HIGH '071'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN072-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN072-HIGH '072'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN073-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN073-HIGH '073'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN074-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN074-HIGH '074'.
AT SELECTION-SCREEN ON VALUE-REQUEST FOR %%DYN075-HIGH.
  PERFORM AT_SEL_ON_VAL USING 'HIGH' %%DYN075-HIGH '075'.
