***INCLUDE RSDBCOM4.
* Gemeinsames INCLUDE RSDBRUNT/SAPDBxyz

* TYPES-Definitionen
TYPE-POOLS RSDS.

* Dynamische Selektionen
DATA BEGIN OF COMMON PART %_DYN_SEL ##COMMON_PART_NEEDED.
  DATA DYN_SEL TYPE RSDS_TYPE.
DATA END   OF COMMON PART %_DYN_SEL.
