* ----------------- SY-SUBTY ----------------------------------------- *
* SUBTY_NO_SELSCREEN: SUBMIT ohne Selektionsbild
CONSTANTS SUBTY_NO_SELSCREEN TYPE X VALUE '08'.
* SUBTY_WITH_SELTAB: SUBMIT WITH SELECTION-TABLE
CONSTANTS SUBTY_WITH_SELTAB TYPE X VALUE '10'.
* SUBTY_FOREIGN_VARIANTS: SUBMIT USING SELECTION-SETS OF PROGRAM
CONSTANTS SUBTY_FOREIGN_VARIS TYPE X VALUE '40'.
* SUBTY_TO_SAPSPOOL:      SUBMIT TO SAP-SPOOL
CONSTANTS SUBTY_TO_SAPSPOOL   TYPE X VALUE '02'.

* ----------------- HEAD-FLAG1 --------------------------------------- *
* PGHD_F1_S1000: Selektionsbild 1000 vorhanden
CONSTANTS PGHD_F1_S1000   TYPE X VALUE '01'.
* PGHD_F1_ADDSC: Zusätzliches Selektionsbild vorhanden
CONSTANTS PGHD_F1_ADDSC   TYPE X VALUE '02'.
